[package]
name = "prompt_smith_web"
version = "0.1.0-alpha.1"
description = "Browser WebAssembly bridge for Prompt Smith"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
prompt_smith_core = { version = "=0.1.0-alpha.1", path = "../prompt_smith_core" }
serde.workspace = true
wasm-bindgen.workspace = true
serde_json.workspace = true
